# Generated by Django 5.0.1 on 2024-03-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
